In [1]:
# 1. 利用 Tensor 创建两个大小分别 3×2 和 4×2 的随机数矩阵 P 和 Q ，要求服从均值为0，标准差0.01为的正态分布

import torch

# 设置随机种子，以便结果重现
torch.manual_seed(25)

P = torch.normal(mean=0.0, std=0.01, size=(3, 2))
Q = torch.normal(mean=0.0, std=0.01, size=(4, 2))

print("Matrix P (3×2):")
print(P)
print("Shape of P:", P.shape)
print("Mean of P: {:.6f}".format(P.mean().item()))
print("Standard deviation of P: {:.6f}".format(P.std().item()))

print("\nMatrix Q (4×2):")
print(Q)
print("Shape of Q:", Q.shape)
print("Mean of Q: {:.6f}".format(Q.mean().item()))
print("Standard deviation of Q: {:.6f}".format(Q.std().item()))

Matrix P (3×2):
tensor([[ 0.0118,  0.0011],
        [ 0.0153,  0.0063],
        [ 0.0090, -0.0040]])
Shape of P: torch.Size([3, 2])
Mean of P: 0.006572
Standard deviation of P: 0.007103

Matrix Q (4×2):
tensor([[ 0.0029, -0.0066],
        [ 0.0095,  0.0146],
        [ 0.0114,  0.0033],
        [-0.0307, -0.0037]])
Shape of Q: torch.Size([4, 2])
Mean of Q: 0.000096
Standard deviation of Q: 0.014404


In [2]:
# 2. 对第二步得到的矩阵 Q (4×2) 进行形状变换得到 Q 的转置 Q^T
Q_T = Q.T
# Q_T = Q.transpose(0, 1)
# Q_T = Q.permute(1, 0)

print("Transpose of Q (size: 2×4):")
print(Q_T)
print("Shape of Q^T:", Q_T.shape)

Transpose of Q (size: 2×4):
tensor([[ 0.0029,  0.0095,  0.0114, -0.0307],
        [-0.0066,  0.0146,  0.0033, -0.0037]])
Shape of Q^T: torch.Size([2, 4])


In [3]:
# 3. 对上述得到的矩阵 P 和矩阵 Q^T 求矩阵相乘
Res = torch.matmul(P, Q_T)
# Res = P @ Q_T

print("Result R = P × Q^T (3×4):")
print(Res)
print("Shape of Res:", Res.shape)

print(f"Shape of P: {P.shape}")
print(f"Shape of Q^T: {Q_T.shape}") 

Result R = P × Q^T (3×4):
tensor([[ 2.7155e-05,  1.2783e-04,  1.3812e-04, -3.6551e-04],
        [ 2.8626e-06,  2.3801e-04,  1.9592e-04, -4.9344e-04],
        [ 5.2535e-05,  2.7291e-05,  8.9510e-05, -2.6138e-04]])
Shape of Res: torch.Size([3, 4])
Shape of P: torch.Size([3, 2])
Shape of Q^T: torch.Size([2, 4])
